[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "k-sounds-hub"
version = "0.4.3"
description = "PipeWire-first modular Linux audio hub"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
authors = [
  { name = "Kooy" }
]
dependencies = [
  "PySide6>=6.6",
  "numpy>=1.26"
]

[project.optional-dependencies]
dev = [
  "pytest>=8.0",
  "ruff>=0.6"
]

[project.scripts]
k-sounds-hub = "ksound_hub.app:main"
ksound-hub = "ksound_hub.app:main"
ksound-control = "ksound_hub.control:main"
k-sounds-hub-glass = "ksound_hub.glass_app:main"
ksound-hub-glass = "ksound_hub.glass_app:main"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
ksound_hub = [
  "assets/*",
  "assets/**/*"
]

[tool.ruff]
line-length = 100
target-version = "py311"
